version: '3.7'

services:
    web-app:
        container_name: "leave-manager"
        image: chrisshi/leave-manager:webapp-latest
        expose:
            - "8000"
        environment:
            - NODE_ENV='production'
            - PORT='8000'
        volumes:
            - react_volume:/home/node/app/client/build
        networks:
            - app-network
            - reverse-proxy
        depends_on:
            - mongo-db
    mongo-db:
        image: mongo:4.2.2-bionic
        networks:
            - app-network
        volumes:
            - mongo_volume:/data/db

networks:
    app-network:
        driver: bridge
    reverse-proxy:
        external: true
volumes:
    react_volume:
    mongo_volume:
